### ISSUE TITLE
Error enabling the plugin

### ISSUE THREAD

**Issue by hildevestol** [raulanatol/camaleon-media_aws_s3#1]
Hi. When I try to enable this plugin I get an error.. Instantly after enabling the plugin I get this error:

![screen shot 2015-09-23 at 19 12 22](https://cloud.githubusercontent.com/assets/1770947/10052459/5312b8d0-6227-11e5-823e-813258d525d4.png)

And then I am stuck with an error on every page in the admin, f.eks. this:

![screen shot 2015-09-23 at 19 13 56](https://cloud.githubusercontent.com/assets/1770947/10052473/678a465c-6227-11e5-8cd0-7c9ea8d67038.png)

When I stop the server, it won't start up again.. gettting this error: 

```
Exiting
/Users/hilde/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/camaleon_cms-0.2.1/config/routes/admin.rb:120:in `eval': 'plugins/camaleon-media_aws_s3-master/admin' is not a supported controller name. This can lead to potential routing problems. See http://guides.rubyonrails.org/routing.html#specifying-a-controller-to-use (ArgumentError)
```

**Comment by raulanatol** [comment]
Hi @hildevestol!

Try to change the name of the plugin folder.

current: camaleon-media_aws_s3-master
try with: **media_aws_s3**

Regards!

**Comment by hildevestol** [comment]
That works! Thx. 
I downloaded the plugin and followed the instructions here => http://camaleon.tuzitio.com/store/plugins/11

So perhaps the downloaded zip should be renamed or add a line in the installation instructions that the folder name has to be **media_aws_s3**?

**Comment by raulanatol** [comment]
You are absolutely right. The documentation is very scarce. I will add more in the next version.

**Comment by hildevestol** [comment]
@raulanatol what am I supposed to put in `CDN Base path URL`? Is it a path to amazon, or something of my choosing? No matter what I put there I get a js error when I click on the folder icon in Insert/edit image. 
![screen shot 2015-09-23 at 20 24 12](https://cloud.githubusercontent.com/assets/1770947/10054405/2a3b34b4-6231-11e5-92a1-818495ca140e.png)

**Comment by raulanatol** [comment]
Hi @hildevestol!

Sorry the plugin is in beta yet :(

The CDN Base path URL represent the url of the cdn for access to the files.

Test with: https://YOUR_BUCKET_NAME.s3.amazonaws.com

Regards

**Comment by hildevestol** [comment]
Ok. I tried that.. so this error is probably a bug then :smile: 
Thank you for working on this plugin! And I look forward to keep testing it :+1: 

```
TypeError: undefined is not a function (evaluating 'this.startsWith('http://')')
```

It seems to be this that is failing.

``` javascript
String.prototype.to_url = function () {
  if (this.startsWith('http://') || this.startsWith('https://')) {
    return this;
  } else {
    return root_url.slice(0, root_url.length - 1) + this;
  }
};
```

**Comment by raulanatol** [comment]
Hi @hildevestol 

I was trying and I can't reproduce it.
Can you say what is your CDN base path?

Maybe you put a slash to the end of the URL?

Regards

**Comment by hildevestol** [comment]
The url I'm using is https://blog-engine-test.s3.amazonaws.com

![screen shot 2015-09-25 at 09 23 32](https://cloud.githubusercontent.com/assets/1770947/10095144/e4eee53a-6367-11e5-836c-4d8687aac6ec.png)

I'm using Safari on OSX, when I tried in Firefox I got a different error.
![screen shot 2015-09-25 at 09 27 26](https://cloud.githubusercontent.com/assets/1770947/10095160/ffed58c6-6367-11e5-9a0c-5bc1d694f819.png)

I use this amazone bucket in another testproject and that works just fine, so I believe I should have sufficient rights to the bucket.

**Comment by raulanatol** [comment]
Hi!

It may be a problem with the cache.
Could you make a test?

Go to _/app/apps/plugins/media_aws_s3/models/cache_connector.rb_ and change the initialize method for this:

```
 def initialize
 super(Rails.cache)
 end
```

So you will active the default rails cache instead of redis cache.

Regards

**Comment by hildevestol** [comment]
That seems to help. I get the folders from the bucket now.
But when I try to upload a image it looks like nothing is happening. But I find the pictures in my bucket when checking s3, but they doesn't appear in the media manager.

**Comment by lmany** [comment]
Hi, 
I have the same issue

**Comment by raulanatol** [comment]
I'm sorry for the inconvenience.
We be planning to change to carrierwave, fog.
Please follow this issue to more information (https://github.com/owen2345/camaleon-cms/issues/107)
Regards!

**Comment by hildevestol** [comment]
Alright! Looking forward to that!
