### ISSUE TITLE
memcached incompatible version error

### ISSUE THREAD

**Issue by norbajunior** [raulanatol/camaleon-media_aws_s3#3]
Hi @raulanatol 

I'm getting this error when I try run the `rails s`. Do you know what I can do to solve it?

/Users/norba/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require': incompatible library version - /Users/norba/.rvm/gems/ruby-2.2-head/gems/memcached-1.8.0/lib/rlibmemcached.bundle (fatal)
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in`block in require'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in`require'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/memcached-1.8.0/lib/memcached.rb:19:in `<top (required)>'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in`require'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in`load_dependency'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/el_finder_s3-0.1.1/lib/el_finder_s3/adapter.rb:2:in`module:ElFinderS3'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/el_finder_s3-0.1.1/lib/el_finder_s3/adapter.rb:1:in `<top (required)>'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in`require'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in`load_dependency'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/el_finder_s3-0.1.1/lib/el_finder_s3.rb:7:in`<top (required)>'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in`block (2 levels) in require'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in`block in require'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in`require'
    from /Users/norba/.rvm/gems/ruby-2.2-head/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
    from /Users/norba/Sites/iterar/knok-blog-rails/config/application.rb:7:in`<top (required)>'
    from /Users/norba/.rvm/rubies/ruby-2.2-head/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /Users/norba/.rvm/rubies/ruby-2.2-head/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /Users/norba/Sites/iterar/knok-blog-rails/Rakefile:4:in `<top (required)>'
    from /Users/norba/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/rake/rake_module.rb:28:in`load'
    from /Users/norba/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/rake/rake_module.rb:28:in `load_rakefile'
    from /Users/norba/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/rake/application.rb:689:in`raw_load_rakefile'
    from /Users/norba/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/rake/application.rb:94:in `block in load_rakefile'
    from /Users/norba/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/rake/application.rb:176:in`standard_exception_handling'
    from /Users/norba/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/rake/application.rb:93:in `load_rakefile'
    from /Users/norba/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/rake/application.rb:77:in`block in run'
    from /Users/norba/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
    from /Users/norba/.rvm/rubies/ruby-2.2-head/lib/ruby/2.2.0/rake/application.rb:75:in`run'
    from /Users/norba/.rvm/rubies/ruby-2.2-head/bin/rake:33:in `<main>'

**Comment by raulanatol** [comment]
Hi @norbajunior 

I'm so sorry for the long delay of my response.
Now I'm working to make aws s3 native in camaleon_cms. For this reason I have not upgraded this plugin.

But if you keep using...
The cache configuration is in the /app/apps/plugins/media_aws_s3/models/cache_connector.rb file.
You can specify your preferred cache system. This plugin are using https://rubygems.org/gems/cache gem to wrap caches.

For example if you can use Rails.cache:

```
class Plugins::MediaAwsS3::Models::CacheConnector < ElFinderS3::CacheConnector

 def initialize
 super(Rails.cache)
 end

end
```

If you can show more information: https://github.com/raulanatol/el_finder_s3
Regards.

**Comment by nathanielks** [comment]
@norbajunior I'm experiencing this error as well, but while not using this gem. Were you ever able to resolve it?

**Comment by norbajunior** [comment]
Hey guys, sorry for taking so long. I ended up not using the gem due to some changes on the project I worked, since then I haven't tried to solve the problem.
